package com.uberhelixx.flatlights;

import com.google.common.collect.Ordering;
import com.uberhelixx.flatlights.block.ModBlocks;
import com.uberhelixx.flatlights.item.ModItems;
import com.uberhelixx.flatlights.item.curio.ModCurios;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;

import java.util.Arrays;
import java.util.Comparator;
import java.util.List;

@Mod.EventBusSubscriber(modid = FlatLights.MOD_ID, bus = Mod.EventBusSubscriber.Bus.MOD)
public class FlatLightsTabSort {
    public static Comparator<ItemStack> tabSort;

    @SubscribeEvent
    public static void tabSort(final FMLCommonSetupEvent event) {
        //list of all items for sorting creative inventory tab
        List<Item> itemOrder = Arrays.asList(
            ModBlocks.BLACK_FLATBLOCK.get().asItem(),
            ModBlocks.BLUE_FLATBLOCK.get().asItem(),
            ModBlocks.BROWN_FLATBLOCK.get().asItem(),
            ModBlocks.CYAN_FLATBLOCK.get().asItem(),
            ModBlocks.GRAY_FLATBLOCK.get().asItem(),
            ModBlocks.GREEN_FLATBLOCK.get().asItem(),
            ModBlocks.LIGHT_BLUE_FLATBLOCK.get().asItem(),
            ModBlocks.LIGHT_GRAY_FLATBLOCK.get().asItem(),
            ModBlocks.LIME_FLATBLOCK.get().asItem(),
            ModBlocks.MAGENTA_FLATBLOCK.get().asItem(),
            ModBlocks.ORANGE_FLATBLOCK.get().asItem(),
            ModBlocks.PINK_FLATBLOCK.get().asItem(),
            ModBlocks.PURPLE_FLATBLOCK.get().asItem(),
            ModBlocks.RED_FLATBLOCK.get().asItem(),
            ModBlocks.WHITE_FLATBLOCK.get().asItem(),
            ModBlocks.YELLOW_FLATBLOCK.get().asItem(),

            ModBlocks.SALMON_FLATBLOCK.get().asItem(),
            ModBlocks.GOLD_FLATBLOCK.get().asItem(),
            ModBlocks.SANDY_YELLOW_FLATBLOCK.get().asItem(),
            ModBlocks.PALE_YELLOW_FLATBLOCK.get().asItem(),
            ModBlocks.SPRING_GREEN_FLATBLOCK.get().asItem(),
            ModBlocks.PASTEL_GREEN_FLATBLOCK.get().asItem(),
            ModBlocks.TEAL_FLATBLOCK.get().asItem(),
            ModBlocks.CYAN_BLUE_FLATBLOCK.get().asItem(),
            ModBlocks.CERULEAN_FLATBLOCK.get().asItem(),
            ModBlocks.SAPPHIRE_FLATBLOCK.get().asItem(),
            ModBlocks.NAVY_BLUE_FLATBLOCK.get().asItem(),
            ModBlocks.INDIGO_FLATBLOCK.get().asItem(),
            ModBlocks.DARK_PURPLE_FLATBLOCK.get().asItem(),
            ModBlocks.RED_PURPLE_FLATBLOCK.get().asItem(),
            ModBlocks.DARK_PINK_FLATBLOCK.get().asItem(),
            ModBlocks.ROSY_PINK_FLATBLOCK.get().asItem(),

            ModBlocks.BLACK_HEXBLOCK.get().asItem(),
            ModBlocks.BLUE_HEXBLOCK.get().asItem(),
            ModBlocks.BROWN_HEXBLOCK.get().asItem(),
            ModBlocks.CYAN_HEXBLOCK.get().asItem(),
            ModBlocks.GRAY_HEXBLOCK.get().asItem(),
            ModBlocks.GREEN_HEXBLOCK.get().asItem(),
            ModBlocks.LIGHT_BLUE_HEXBLOCK.get().asItem(),
            ModBlocks.LIGHT_GRAY_HEXBLOCK.get().asItem(),
            ModBlocks.LIME_HEXBLOCK.get().asItem(),
            ModBlocks.MAGENTA_HEXBLOCK.get().asItem(),
            ModBlocks.ORANGE_HEXBLOCK.get().asItem(),
            ModBlocks.PINK_HEXBLOCK.get().asItem(),
            ModBlocks.PURPLE_HEXBLOCK.get().asItem(),
            ModBlocks.RED_HEXBLOCK.get().asItem(),
            ModBlocks.WHITE_HEXBLOCK.get().asItem(),
            ModBlocks.YELLOW_HEXBLOCK.get().asItem(),

            ModBlocks.SALMON_HEXBLOCK.get().asItem(),
            ModBlocks.GOLD_HEXBLOCK.get().asItem(),
            ModBlocks.SANDY_YELLOW_HEXBLOCK.get().asItem(),
            ModBlocks.PALE_YELLOW_HEXBLOCK.get().asItem(),
            ModBlocks.SPRING_GREEN_HEXBLOCK.get().asItem(),
            ModBlocks.PASTEL_GREEN_HEXBLOCK.get().asItem(),
            ModBlocks.TEAL_HEXBLOCK.get().asItem(),
            ModBlocks.CYAN_BLUE_HEXBLOCK.get().asItem(),
            ModBlocks.CERULEAN_HEXBLOCK.get().asItem(),
            ModBlocks.SAPPHIRE_HEXBLOCK.get().asItem(),
            ModBlocks.NAVY_BLUE_HEXBLOCK.get().asItem(),
            ModBlocks.INDIGO_HEXBLOCK.get().asItem(),
            ModBlocks.DARK_PURPLE_HEXBLOCK.get().asItem(),
            ModBlocks.RED_PURPLE_HEXBLOCK.get().asItem(),
            ModBlocks.DARK_PINK_HEXBLOCK.get().asItem(),
            ModBlocks.ROSY_PINK_HEXBLOCK.get().asItem(),

            ModBlocks.BLACK_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.BLUE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.BROWN_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.CYAN_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.GRAY_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.GREEN_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.LIGHT_BLUE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.LIGHT_GRAY_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.LIME_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.MAGENTA_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.ORANGE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.PINK_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.PURPLE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.RED_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.WHITE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.YELLOW_LARGE_HEXBLOCK.get().asItem(),

            ModBlocks.SALMON_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.GOLD_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.SANDY_YELLOW_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.PALE_YELLOW_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.SPRING_GREEN_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.PASTEL_GREEN_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.TEAL_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.CYAN_BLUE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.CERULEAN_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.SAPPHIRE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.NAVY_BLUE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.INDIGO_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.DARK_PURPLE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.RED_PURPLE_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.DARK_PINK_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.ROSY_PINK_LARGE_HEXBLOCK.get().asItem(),

            ModBlocks.BLACK_TILES.get().asItem(),
            ModBlocks.BLUE_TILES.get().asItem(),
            ModBlocks.BROWN_TILES.get().asItem(),
            ModBlocks.CYAN_TILES.get().asItem(),
            ModBlocks.GRAY_TILES.get().asItem(),
            ModBlocks.GREEN_TILES.get().asItem(),
            ModBlocks.LIGHT_BLUE_TILES.get().asItem(),
            ModBlocks.LIGHT_GRAY_TILES.get().asItem(),
            ModBlocks.LIME_TILES.get().asItem(),
            ModBlocks.MAGENTA_TILES.get().asItem(),
            ModBlocks.ORANGE_TILES.get().asItem(),
            ModBlocks.PINK_TILES.get().asItem(),
            ModBlocks.PURPLE_TILES.get().asItem(),
            ModBlocks.RED_TILES.get().asItem(),
            ModBlocks.WHITE_TILES.get().asItem(),
            ModBlocks.YELLOW_TILES.get().asItem(),

            ModBlocks.SALMON_TILES.get().asItem(),
            ModBlocks.GOLD_TILES.get().asItem(),
            ModBlocks.SANDY_YELLOW_TILES.get().asItem(),
            ModBlocks.PALE_YELLOW_TILES.get().asItem(),
            ModBlocks.SPRING_GREEN_TILES.get().asItem(),
            ModBlocks.PASTEL_GREEN_TILES.get().asItem(),
            ModBlocks.TEAL_TILES.get().asItem(),
            ModBlocks.CYAN_BLUE_TILES.get().asItem(),
            ModBlocks.CERULEAN_TILES.get().asItem(),
            ModBlocks.SAPPHIRE_TILES.get().asItem(),
            ModBlocks.NAVY_BLUE_TILES.get().asItem(),
            ModBlocks.INDIGO_TILES.get().asItem(),
            ModBlocks.DARK_PURPLE_TILES.get().asItem(),
            ModBlocks.RED_PURPLE_TILES.get().asItem(),
            ModBlocks.DARK_PINK_TILES.get().asItem(),
            ModBlocks.ROSY_PINK_TILES.get().asItem(),

            ModBlocks.BLACK_LARGE_TILES.get().asItem(),
            ModBlocks.BLUE_LARGE_TILES.get().asItem(),
            ModBlocks.BROWN_LARGE_TILES.get().asItem(),
            ModBlocks.CYAN_LARGE_TILES.get().asItem(),
            ModBlocks.GRAY_LARGE_TILES.get().asItem(),
            ModBlocks.GREEN_LARGE_TILES.get().asItem(),
            ModBlocks.LIGHT_BLUE_LARGE_TILES.get().asItem(),
            ModBlocks.LIGHT_GRAY_LARGE_TILES.get().asItem(),
            ModBlocks.LIME_LARGE_TILES.get().asItem(),
            ModBlocks.MAGENTA_LARGE_TILES.get().asItem(),
            ModBlocks.ORANGE_LARGE_TILES.get().asItem(),
            ModBlocks.PINK_LARGE_TILES.get().asItem(),
            ModBlocks.PURPLE_LARGE_TILES.get().asItem(),
            ModBlocks.RED_LARGE_TILES.get().asItem(),
            ModBlocks.WHITE_LARGE_TILES.get().asItem(),
            ModBlocks.YELLOW_LARGE_TILES.get().asItem(),

            ModBlocks.SALMON_LARGE_TILES.get().asItem(),
            ModBlocks.GOLD_LARGE_TILES.get().asItem(),
            ModBlocks.SANDY_YELLOW_LARGE_TILES.get().asItem(),
            ModBlocks.PALE_YELLOW_LARGE_TILES.get().asItem(),
            ModBlocks.SPRING_GREEN_LARGE_TILES.get().asItem(),
            ModBlocks.PASTEL_GREEN_LARGE_TILES.get().asItem(),
            ModBlocks.TEAL_LARGE_TILES.get().asItem(),
            ModBlocks.CYAN_BLUE_LARGE_TILES.get().asItem(),
            ModBlocks.CERULEAN_LARGE_TILES.get().asItem(),
            ModBlocks.SAPPHIRE_LARGE_TILES.get().asItem(),
            ModBlocks.NAVY_BLUE_LARGE_TILES.get().asItem(),
            ModBlocks.INDIGO_LARGE_TILES.get().asItem(),
            ModBlocks.DARK_PURPLE_LARGE_TILES.get().asItem(),
            ModBlocks.RED_PURPLE_LARGE_TILES.get().asItem(),
            ModBlocks.DARK_PINK_LARGE_TILES.get().asItem(),
            ModBlocks.ROSY_PINK_LARGE_TILES.get().asItem(),

            ModBlocks.BLACK_PANEL.get().asItem(),
            ModBlocks.BLUE_PANEL.get().asItem(),
            ModBlocks.BROWN_PANEL.get().asItem(),
            ModBlocks.CYAN_PANEL.get().asItem(),
            ModBlocks.GRAY_PANEL.get().asItem(),
            ModBlocks.GREEN_PANEL.get().asItem(),
            ModBlocks.LIGHT_BLUE_PANEL.get().asItem(),
            ModBlocks.LIGHT_GRAY_PANEL.get().asItem(),
            ModBlocks.LIME_PANEL.get().asItem(),
            ModBlocks.MAGENTA_PANEL.get().asItem(),
            ModBlocks.ORANGE_PANEL.get().asItem(),
            ModBlocks.PINK_PANEL.get().asItem(),
            ModBlocks.PURPLE_PANEL.get().asItem(),
            ModBlocks.RED_PANEL.get().asItem(),
            ModBlocks.WHITE_PANEL.get().asItem(),
            ModBlocks.YELLOW_PANEL.get().asItem(),

            ModBlocks.SALMON_PANEL.get().asItem(),
            ModBlocks.GOLD_PANEL.get().asItem(),
            ModBlocks.SANDY_YELLOW_PANEL.get().asItem(),
            ModBlocks.PALE_YELLOW_PANEL.get().asItem(),
            ModBlocks.SPRING_GREEN_PANEL.get().asItem(),
            ModBlocks.PASTEL_GREEN_PANEL.get().asItem(),
            ModBlocks.TEAL_PANEL.get().asItem(),
            ModBlocks.CYAN_BLUE_PANEL.get().asItem(),
            ModBlocks.CERULEAN_PANEL.get().asItem(),
            ModBlocks.SAPPHIRE_PANEL.get().asItem(),
            ModBlocks.NAVY_BLUE_PANEL.get().asItem(),
            ModBlocks.INDIGO_PANEL.get().asItem(),
            ModBlocks.DARK_PURPLE_PANEL.get().asItem(),
            ModBlocks.RED_PURPLE_PANEL.get().asItem(),
            ModBlocks.DARK_PINK_PANEL.get().asItem(),
            ModBlocks.ROSY_PINK_PANEL.get().asItem(),

            ModBlocks.BLACK_PILLAR.get().asItem(),
            ModBlocks.BLUE_PILLAR.get().asItem(),
            ModBlocks.BROWN_PILLAR.get().asItem(),
            ModBlocks.CYAN_PILLAR.get().asItem(),
            ModBlocks.GRAY_PILLAR.get().asItem(),
            ModBlocks.GREEN_PILLAR.get().asItem(),
            ModBlocks.LIGHT_BLUE_PILLAR.get().asItem(),
            ModBlocks.LIGHT_GRAY_PILLAR.get().asItem(),
            ModBlocks.LIME_PILLAR.get().asItem(),
            ModBlocks.MAGENTA_PILLAR.get().asItem(),
            ModBlocks.ORANGE_PILLAR.get().asItem(),
            ModBlocks.PINK_PILLAR.get().asItem(),
            ModBlocks.PURPLE_PILLAR.get().asItem(),
            ModBlocks.RED_PILLAR.get().asItem(),
            ModBlocks.WHITE_PILLAR.get().asItem(),
            ModBlocks.YELLOW_PILLAR.get().asItem(),

            ModBlocks.SALMON_PILLAR.get().asItem(),
            ModBlocks.GOLD_PILLAR.get().asItem(),
            ModBlocks.SANDY_YELLOW_PILLAR.get().asItem(),
            ModBlocks.PALE_YELLOW_PILLAR.get().asItem(),
            ModBlocks.SPRING_GREEN_PILLAR.get().asItem(),
            ModBlocks.PASTEL_GREEN_PILLAR.get().asItem(),
            ModBlocks.TEAL_PILLAR.get().asItem(),
            ModBlocks.CYAN_BLUE_PILLAR.get().asItem(),
            ModBlocks.CERULEAN_PILLAR.get().asItem(),
            ModBlocks.SAPPHIRE_PILLAR.get().asItem(),
            ModBlocks.NAVY_BLUE_PILLAR.get().asItem(),
            ModBlocks.INDIGO_PILLAR.get().asItem(),
            ModBlocks.DARK_PURPLE_PILLAR.get().asItem(),
            ModBlocks.RED_PURPLE_PILLAR.get().asItem(),
            ModBlocks.DARK_PINK_PILLAR.get().asItem(),
            ModBlocks.ROSY_PINK_PILLAR.get().asItem(),

            ModBlocks.BLACK_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.BLUE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.BROWN_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.CYAN_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.GRAY_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.GREEN_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.LIGHT_BLUE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.LIGHT_GRAY_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.LIME_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.MAGENTA_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.ORANGE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.PINK_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.PURPLE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.RED_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.WHITE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.YELLOW_HORIZONTAL_EDGE.get().asItem(),

            ModBlocks.SALMON_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.GOLD_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.SANDY_YELLOW_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.PALE_YELLOW_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.SPRING_GREEN_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.PASTEL_GREEN_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.TEAL_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.CYAN_BLUE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.CERULEAN_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.SAPPHIRE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.NAVY_BLUE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.INDIGO_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.DARK_PURPLE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.RED_PURPLE_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.DARK_PINK_HORIZONTAL_EDGE.get().asItem(),
            ModBlocks.ROSY_PINK_HORIZONTAL_EDGE.get().asItem(),

            ModBlocks.BLACK_VERTICAL_EDGE.get().asItem(),
            ModBlocks.BLUE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.BROWN_VERTICAL_EDGE.get().asItem(),
            ModBlocks.CYAN_VERTICAL_EDGE.get().asItem(),
            ModBlocks.GRAY_VERTICAL_EDGE.get().asItem(),
            ModBlocks.GREEN_VERTICAL_EDGE.get().asItem(),
            ModBlocks.LIGHT_BLUE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.LIGHT_GRAY_VERTICAL_EDGE.get().asItem(),
            ModBlocks.LIME_VERTICAL_EDGE.get().asItem(),
            ModBlocks.MAGENTA_VERTICAL_EDGE.get().asItem(),
            ModBlocks.ORANGE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.PINK_VERTICAL_EDGE.get().asItem(),
            ModBlocks.PURPLE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.RED_VERTICAL_EDGE.get().asItem(),
            ModBlocks.WHITE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.YELLOW_VERTICAL_EDGE.get().asItem(),

            ModBlocks.SALMON_VERTICAL_EDGE.get().asItem(),
            ModBlocks.GOLD_VERTICAL_EDGE.get().asItem(),
            ModBlocks.SANDY_YELLOW_VERTICAL_EDGE.get().asItem(),
            ModBlocks.PALE_YELLOW_VERTICAL_EDGE.get().asItem(),
            ModBlocks.SPRING_GREEN_VERTICAL_EDGE.get().asItem(),
            ModBlocks.PASTEL_GREEN_VERTICAL_EDGE.get().asItem(),
            ModBlocks.TEAL_VERTICAL_EDGE.get().asItem(),
            ModBlocks.CYAN_BLUE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.CERULEAN_VERTICAL_EDGE.get().asItem(),
            ModBlocks.SAPPHIRE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.NAVY_BLUE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.INDIGO_VERTICAL_EDGE.get().asItem(),
            ModBlocks.DARK_PURPLE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.RED_PURPLE_VERTICAL_EDGE.get().asItem(),
            ModBlocks.DARK_PINK_VERTICAL_EDGE.get().asItem(),
            ModBlocks.ROSY_PINK_VERTICAL_EDGE.get().asItem(),

            ModBlocks.BLACK_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.BLUE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.BROWN_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.GRAY_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.GREEN_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_BLUE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_GRAY_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.LIME_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.MAGENTA_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.ORANGE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.PINK_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.PURPLE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.RED_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.WHITE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.YELLOW_FLATBLOCK_BLACKOUT.get().asItem(),

            ModBlocks.SALMON_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.GOLD_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.SANDY_YELLOW_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.PALE_YELLOW_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.SPRING_GREEN_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.PASTEL_GREEN_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.TEAL_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_BLUE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.CERULEAN_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.SAPPHIRE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.NAVY_BLUE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.INDIGO_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PURPLE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.RED_PURPLE_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PINK_FLATBLOCK_BLACKOUT.get().asItem(),
            ModBlocks.ROSY_PINK_FLATBLOCK_BLACKOUT.get().asItem(),

            ModBlocks.BLACK_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.BLUE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.BROWN_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.GRAY_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.GREEN_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_BLUE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_GRAY_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.LIME_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.MAGENTA_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.ORANGE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.PINK_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.PURPLE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.RED_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.WHITE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.YELLOW_PANEL_BLACKOUT.get().asItem(),

            ModBlocks.SALMON_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.GOLD_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.SANDY_YELLOW_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.PALE_YELLOW_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.SPRING_GREEN_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.PASTEL_GREEN_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.TEAL_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_BLUE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.CERULEAN_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.SAPPHIRE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.NAVY_BLUE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.INDIGO_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PURPLE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.RED_PURPLE_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PINK_PANEL_BLACKOUT.get().asItem(),
            ModBlocks.ROSY_PINK_PANEL_BLACKOUT.get().asItem(),

            ModBlocks.BLACK_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.BLUE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.BROWN_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.GRAY_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.GREEN_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_BLUE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_GRAY_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.LIME_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.MAGENTA_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.ORANGE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.PINK_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.PURPLE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.RED_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.WHITE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.YELLOW_PILLAR_BLACKOUT.get().asItem(),

            ModBlocks.SALMON_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.GOLD_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.SANDY_YELLOW_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.PALE_YELLOW_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.SPRING_GREEN_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.PASTEL_GREEN_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.TEAL_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_BLUE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.CERULEAN_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.SAPPHIRE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.NAVY_BLUE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.INDIGO_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PURPLE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.RED_PURPLE_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PINK_PILLAR_BLACKOUT.get().asItem(),
            ModBlocks.ROSY_PINK_PILLAR_BLACKOUT.get().asItem(),

            ModBlocks.BLACK_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.BLUE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.BROWN_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.GRAY_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.GREEN_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_BLUE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_GRAY_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.LIME_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.MAGENTA_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.ORANGE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PINK_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PURPLE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.RED_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.WHITE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.YELLOW_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),

            ModBlocks.SALMON_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.GOLD_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.SANDY_YELLOW_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PALE_YELLOW_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.SPRING_GREEN_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PASTEL_GREEN_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.TEAL_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_BLUE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.CERULEAN_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.SAPPHIRE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.NAVY_BLUE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.INDIGO_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PURPLE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.RED_PURPLE_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PINK_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.ROSY_PINK_HORIZONTAL_EDGE_BLACKOUT.get().asItem(),

            ModBlocks.BLACK_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.BLUE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.BROWN_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.GRAY_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.GREEN_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_BLUE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.LIGHT_GRAY_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.LIME_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.MAGENTA_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.ORANGE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PINK_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PURPLE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.RED_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.WHITE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.YELLOW_VERTICAL_EDGE_BLACKOUT.get().asItem(),

            ModBlocks.SALMON_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.GOLD_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.SANDY_YELLOW_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PALE_YELLOW_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.SPRING_GREEN_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.PASTEL_GREEN_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.TEAL_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.CYAN_BLUE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.CERULEAN_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.SAPPHIRE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.NAVY_BLUE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.INDIGO_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PURPLE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.RED_PURPLE_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.DARK_PINK_VERTICAL_EDGE_BLACKOUT.get().asItem(),
            ModBlocks.ROSY_PINK_VERTICAL_EDGE_BLACKOUT.get().asItem(),

            ModBlocks.GLASS_FLATBLOCK.get().asItem(),
            ModBlocks.GLASS_HEXBLOCK.get().asItem(),
            ModBlocks.GLASS_LARGE_HEXBLOCK.get().asItem(),
            ModBlocks.GLASS_TILES.get().asItem(),
            ModBlocks.GLASS_LARGE_TILES.get().asItem(),

            ModBlocks.PRISMATIC_BLOCK.get().asItem(),
            ModBlocks.PRISMATIC_BLOCK_BLACKOUT.get().asItem(),

            ModBlocks.PLATING_MACHINE.get().asItem(),
            ModBlocks.SPECTRALIZER.get().asItem(),
            ModBlocks.LIGHT_STORAGE.get().asItem(),

            ModItems.PRISMATIC_INGOT.get(),

            ModItems.HELMET_CORE.get(),
            ModItems.CHEST_CORE.get(),
            ModItems.PANTS_CORE.get(),
            ModItems.BOOTS_CORE.get(),

            ModItems.PRISMATIC_HELMET.get(),
            ModItems.PRISMATIC_CHESTPLATE.get(),
            ModItems.PRISMATIC_LEGGINGS.get(),
            ModItems.PRISMATIC_BOOTS.get(),

            ModItems.PRISMATIC_SWORD.get(),
            ModItems.PRISMATIC_BLADE.get(),
            ModItems.PRISMA_NUCLEUS.get(),
            ModItems.PORTABLE_BLACKHOLE.get(),
            ModItems.GRAVITY_LIFT.get(),
            ModItems.BIG_BREAD.get(),

            ModItems.BLACK_REUSABLE_DYE.get(),
            ModItems.BLUE_REUSABLE_DYE.get(),
            ModItems.BROWN_REUSABLE_DYE.get(),
            ModItems.CYAN_REUSABLE_DYE.get(),
            ModItems.GRAY_REUSABLE_DYE.get(),
            ModItems.GREEN_REUSABLE_DYE.get(),
            ModItems.LIGHT_BLUE_REUSABLE_DYE.get(),
            ModItems.LIGHT_GRAY_REUSABLE_DYE.get(),
            ModItems.LIME_REUSABLE_DYE.get(),
            ModItems.MAGENTA_REUSABLE_DYE.get(),
            ModItems.ORANGE_REUSABLE_DYE.get(),
            ModItems.PINK_REUSABLE_DYE.get(),
            ModItems.PURPLE_REUSABLE_DYE.get(),
            ModItems.RED_REUSABLE_DYE.get(),
            ModItems.WHITE_REUSABLE_DYE.get(),
            ModItems.YELLOW_REUSABLE_DYE.get(),
            ModItems.HUE_SHIFTING_VIAL.get(),

            ModItems.BLACKOUT_POWDER.get(),

            ModItems.JOGOAT.get(),

            ModItems.GUN_RAT.get(), //creative only items
            ModItems.PRISMATIC_BLADEMK2.get(),
            ModBlocks.MOB_B_GONE.get().asItem(),
            ModBlocks.SPECTRUM_ANVIL.get().asItem(),
            ModBlocks.LIME_BRICK.get().asItem(),
            ModBlocks.MOTIVATIONAL_CHAIR.get().asItem(),

            ModCurios.DRAGONS_FINAL_CUBE.get(), //curios
            ModCurios.DRAGONS_FINAL_PRISM.get(),
            ModCurios.DRAGONS_FINAL_SPHERE.get(),
            ModCurios.SHORE_CUBE.get(),
            ModCurios.SHORE_PRISM.get(),
            ModCurios.SHORE_SPHERE.get(),
            ModCurios.SUN_CUBE.get(),
            ModCurios.SUN_PRISM.get(),
            ModCurios.SUN_SPHERE.get()
            );
        tabSort = Ordering.explicit(itemOrder).onResultOf(ItemStack::getItem);
    }
}
